[versions]
android-gradle-plugin = "8.5.2"
detekt = "1.23.8"
kotlin = "2.2.21"
dokka = "2.1.0"

compose = "1.9.2"

kotlinx-datetime = "0.6.2"

[libraries]
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }

[plugins]
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
